CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS learning;

CREATE TABLE IF NOT EXISTS identity.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(64) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash CHAR(64) NOT NULL,
    role VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_users_login_not_blank CHECK (char_length(btrim(login)) > 0),
    CONSTRAINT chk_users_first_name_not_blank CHECK (char_length(btrim(first_name)) > 0),
    CONSTRAINT chk_users_last_name_not_blank CHECK (char_length(btrim(last_name)) > 0),
    CONSTRAINT chk_users_email_not_blank CHECK (char_length(btrim(email)) > 0),
    CONSTRAINT chk_users_password_hash_len CHECK (char_length(password_hash) = 64),
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'INSTRUCTOR', 'STUDENT')),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'BLOCKED')),
    CONSTRAINT uq_users_login UNIQUE (login),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS auth.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token UUID NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_sessions_token UNIQUE (token),
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id)
        REFERENCES identity.users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    author_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_courses_title_not_blank CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT chk_courses_description_not_blank CHECK (char_length(btrim(description)) > 0),
    CONSTRAINT chk_courses_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT fk_courses_author FOREIGN KEY (author_id)
        REFERENCES identity.users(id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS catalog.lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    position INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_lessons_title_not_blank CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT chk_lessons_description_not_blank CHECK (char_length(btrim(description)) > 0),
    CONSTRAINT chk_lessons_position_positive CHECK (position > 0),
    CONSTRAINT fk_lessons_course FOREIGN KEY (course_id)
        REFERENCES catalog.courses(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_lessons_course_position UNIQUE (course_id, position)
);

CREATE TABLE IF NOT EXISTS learning.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    enrolled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_enrollments_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT fk_enrollments_user FOREIGN KEY (user_id)
        REFERENCES identity.users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_enrollments_course FOREIGN KEY (course_id)
        REFERENCES catalog.courses(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_enrollments_user_course UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS learning.lesson_completions (
    user_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_lesson_completions PRIMARY KEY (user_id, lesson_id),
    CONSTRAINT fk_lesson_completions_user FOREIGN KEY (user_id)
        REFERENCES identity.users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_lesson_completions_lesson FOREIGN KEY (lesson_id)
        REFERENCES catalog.lessons(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id
    ON auth.sessions (user_id);

CREATE INDEX IF NOT EXISTS idx_courses_author_id
    ON catalog.courses (author_id);

CREATE INDEX IF NOT EXISTS idx_courses_status_id
    ON catalog.courses (status, id);

CREATE INDEX IF NOT EXISTS idx_enrollments_course_id
    ON learning.enrollments (course_id);

CREATE INDEX IF NOT EXISTS idx_enrollments_user_id_id
    ON learning.enrollments (user_id, id);

CREATE INDEX IF NOT EXISTS idx_lesson_completions_lesson_id
    ON learning.lesson_completions (lesson_id);

CREATE INDEX IF NOT EXISTS idx_users_first_name_trgm
    ON identity.users
    USING gin (first_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_users_last_name_trgm
    ON identity.users
    USING gin (last_name gin_trgm_ops);
